assets:
  base_dir: /Users/deseer/PycharmProjects/Haruki-Drawing-API/data
  result_asset_path: lunabot_static_images
font:
  dir: /Users/deseer/PycharmProjects/Haruki-Drawing-API/data
  default: 
    default: SourceHanSansSC-Regular
    bold: SourceHanSansSC-Bold
    heavy: SourceHanSansSC-Heavy
    emoji: EmojiOneColor-SVGinOT
  
