assets:
  base_dir: /Users/deseer/PycharmProjects/Haruki-Drawing-API/data
  result_asset_path: lunabot_static_images
  tmp_path: tmp
  tri_paths:
    - /Users/deseer/PycharmProjects/Haruki-Drawing-API/data/lunabot_static_images/triangle/tri1.png
    - /Users/deseer/PycharmProjects/Haruki-Drawing-API/data/lunabot_static_images/triangle/tri2.png
    - /Users/deseer/PycharmProjects/Haruki-Drawing-API/data/lunabot_static_images/triangle/tri3.png
font:
  dir: /Users/deseer/PycharmProjects/Haruki-Drawing-API/data
  default: 
    default: SourceHanSansSC-Regular
    bold: SourceHanSansSC-Bold
    heavy: SourceHanSansSC-Heavy
    emoji: EmojiOneColor-SVGinOT
  
default_thread_pool_size: 8
screenshot_api_path: http://localhost:18080/screenshot